# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: Generate Code
run-name: Generate Code ${{ inputs.timestamp }}

on:
  workflow_dispatch:
    inputs:
      language:
        type: choice
        description: language of the code to generate
        required: true
        default: javascript
        options:
          - javascript
          - java
          - dotnet
          - go
          - python
      repo_link:
        description: typespec definition repo link
        required: true
      timestamp:
        required: true
      github_pat:
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone azure-sdk-for-js-pr repository
      uses: actions/checkout@v4
      with: 
        repository: MaryGao/azure-sdk-for-js-pr
        token: ${{ inputs.github_pat }}
        path: azure-sdk-for-js-pr

    - name: Create a new branch and checkout
      working-directory: azure-sdk-for-js-pr
      run: |
        git checkout -b tsp_${{ inputs.timestamp }}
    
    - name: Generate code
      working-directory: azure-sdk-for-js-pr
      shell: pwsh
      run: |
        ./eng/common/scripts/TypeSpec-Project-Process.ps1 ${{ inputs.repo_link }}

    - name: Commit generated code and push
      working-directory: azure-sdk-for-js-pr
      run: |
        git config --global user.name 'actions-user'
        git config --global user.email 'action@github.com'
        git add .
        git commit -m "generate code"
        git push
